---
- name: ensure deltarpm is installed and latest
  yum: name=deltarpm state=installed
- name: upgrade all packages
  yum: name=* state=latest
# FIXME: for RedHat may need to enable "Optional RPMs"
- name: ensure EPEL installed
  yum: name=epel-release state=installed
- name: ensure libselinux-python installed prior to SELinux
  yum: name=libselinux-python state=installed
- name: Install base packages
  yum: name={{item}} state=installed
  with_items:
    - ntp
    - ntpdate
    - ntp-doc
    - openssh-server
    - openssh-clients
    - vim
    - net-tools
    - firewalld
    - selinux-policy
    - rsyslog
- name: put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive # log actions that would be blocked if state=enforcing
- name: ensure firewalld is running (and enable it at boot)
  service: name=firewalld state=started enabled=yes

# FIXME: These were not in non-ansible meza, but was present in the firewalld
#        role I co-opted.
# - name: set firewalld default zone
#   command: /bin/firewall-cmd --set-default-zone={{default_zone|default('public')}}
#   register: result
#   changed_when: result.stdout == "success"
# - name: set firewalld zone interface
#   command: /bin/firewall-cmd --zone={{item.key}} --change-interface={{item.value}} --permanent
#   with_dict: "{{firewalld_zone_interface|default({})}}"
#   notify: restart firewalld

# Replace the following shell commands:
# chkconfig ntpd on # Activate service
# ntpdate pool.ntp.org # Synchronize the system clock with 0.pool.ntp.org server
# service ntpd start # Start service
- name: Install NTP
  yum: name=ntp state=installed
- name: Ensure NTP is running and enabled as configured.
  service:
    name: ntpd
    state: started
    enabled: yes
- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd

# - name: Write local config shell file
#   template:
#     src: config.sh.j2
#     dest: /opt/meza/config/config.sh

# - name: Write local config PHP file
#   template:
#     src: config.php.j2
#     dest: /opt/meza/config/config.php
