---
- name: "Grant keys to delegated server {{ grant_keys_to_server }}"
  copy:
    src: "/home/meza-ansible/.ssh/{{ item.file }}"
    dest: "/home/meza-ansible/.ssh/{{ item.file }}"
    owner: meza-ansible
    group: wheel
    mode: "{{ item.mode }}"
  delegate_to: "{{ grant_keys_to_server }}"
  with_items:
  - file: id_rsa
    mode: "0600"
  - file: id_rsa.pub
    mode: "0644"
