---
- name: Ensure replication user exists on master.
  mysql_user:
    name: "{{ mysql_replication_user.name }}"
    host: "{{ mysql_replication_user.host | default('%') }}"
    password: "{{ mysql_replication_user.password }}"
    priv: "{{ mysql_replication_user.priv | default('*.*:REPLICATION SLAVE') }}"
    state: present
  when: >
    (mysql_replication_role == 'master')
    and mysql_replication_user
    and (mysql_replication_master != '')

- name: Check slave replication status.
  mysql_replication: mode=getslave
  ignore_errors: true
  register: slave
  when: >
    mysql_replication_role == 'slave'
    and (mysql_replication_master != '')

- debug: { var: slave }

- name: Check if slave needs configuration
  command: /bin/true
  register: slave_needs_configuration
  when: >
    (
      (slave.Is_Slave is defined and not slave.Is_Slave)
      or (slave.Is_Slave is not defined and slave|failed)
      or (slave.Slave_IO_Running == 'No' and slave.Slave_SQL_Running == 'No')
    )

- debug: { var: slave_needs_configuration }

- name: Check master replication status.
  mysql_replication: mode=getmaster
  delegate_to: "{{ mysql_replication_master }}"
  register: master
  when: >
    not slave_needs_configuration|skipped
    and (mysql_replication_role == 'slave')
    and (mysql_replication_master != '')

- debug: { var: master }

- name: Configure replication on the slave.
  mysql_replication:
    mode: changemaster
    master_host: "{{ mysql_replication_master }}"
    master_user: "{{ mysql_replication_user.name }}"
    master_password: "{{ mysql_replication_user.password }}"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  ignore_errors: True
  when: >
    not slave_needs_configuration|skipped
    and (mysql_replication_role == 'slave')
    and (mysql_replication_master != '')
    and mysql_replication_user

- name: Start replication.
  mysql_replication: mode=startslave
  when: >
    not slave_needs_configuration|skipped
    and (mysql_replication_role == 'slave')
    and (mysql_replication_master != '')
