---
#
# Loads MediaWiki extensions as defined in a YAML file.
#
# requires `{{ extfile }}` to be set to either:
#   1) A path to a valid YAML file with extension definitions like
#     - name: CollapsibleVector
#       repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/CollapsibleVector
#       version: REL1_27
#     - name: Another extension ...
#   2) A path to a non-existent file
#
- fail:
    msg: "Using load-extension-from-file.yml without passing 'extfile' param"
  when: extfile is not defined

- stat:
    path: "{{ extfile }}"
  register: extfile_status

- debug:
    msg: "Reading extensions file at {{ extfile }}"
  when: extfile_status.stat.isreg is defined and extfile_status.stat.isreg

- include_vars:
  file: "{{ extfile }}"
  name: extensions_to_load
  when: extfile_status.stat.isreg is defined and extfile_status.stat.isreg

# This is a repeat of the same extensions thing above. need to abstract it.
- name: Ensure all-wiki more-extensions installed
  git:
    repo: "{{ item.repo }}"
    dest: "{{ m_mediawiki }}/extensions/{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ extensions_to_load }}"
  when: extfile_status.stat.isreg is defined and extfile_status.stat.isreg
