---


- name: Ensure proper MediaWiki git version installed
  git:
    repo: https://gerrit.wikimedia.org/r/p/mediawiki/core.git
    dest: "{{ m_mediawiki }}"
    version: "1.27.1"

# The following was required for MediaWiki 1.25.5, and appears fixed in 1.25.6+
#
# Before composer-merge-plugin v1.2.0, MW incorrectly required
# v1.0.0 of the Composer internal composer-plugin-api component.
# Composer recently bumped this internal version to v1.1.0 [0].
# A patch to MW is in work, but this is required to keep meza
# building properly.
#
# [0]: https://github.com/composer/composer/commit/aeafe2fe59992efd1bc3f890b760f1a9c4874e1c
#
# Replace v1.0.0 with v1.3.1 of wikimedia/composer-merge-plugin in composer.json
# sed -r -i 's/"wikimedia\/composer-merge-plugin": "1.0.0",/"wikimedia\/composer-merge-plugin": "1.3.1",/;' "$m_mediawiki/composer.json"



- name: Ensure proper Vector skin git version installed
  git:
    repo: https://gerrit.wikimedia.org/r/p/mediawiki/skins/Vector.git
    dest: "{{ m_mediawiki }}/skins/Vector"
    version: "REL1_27"

- name: Ensure LocalSettings.php in place
  template:
    src: LocalSettings.php.j2
    dest: "{{ m_mediawiki }}/LocalSettings.php"
    backup: yes

# FIXME: that's not where this should be...
- name: Ensure preLocalSettings_allWikis.php in place
  template:
    src: preLocalSettings_allWikis.php.j2
    dest: "{{ m_mediawiki }}/preLocalSettings_allWikis.php"
    backup: yes

- name: Put composer.local.json in place to load composer-supported extensions
  template:
    src: composer.local.json.j2
    dest: "{{ m_mediawiki }}/composer.local.json"

- name: Run composer install on MediaWiki for dependencies and composer-supported extensions
  composer:
    command: install
    working_dir: "{{ m_mediawiki }}"

- name: Ensure proper Vector skin git version installed
  git:
    repo: https://github.com/jamesmontalvo3/WikiBlender.git
    dest: "{{ m_htdocs }}/WikiBlender"
    version: "master"

- name: Ensure BlenderSettings.php in place
  template:
    src: BlenderSettings.php.j2
    dest: "{{ m_htdocs }}/WikiBlender/BlenderSettings.php"
    backup: yes

- name: Ensure extensions installed
  git:
    repo: "{{ item.repo }}"
    dest: "{{ m_mediawiki }}/extensions/{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - name: ParserFunctions
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/ParserFunctions.git
      version: REL1_27
    - name: StringFunctionsEscaped
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/StringFunctionsEscaped.git
      version: REL1_27
    - name: ExternalData
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/ExternalData.git
      version: REL1_27
    - name: LabeledSectionTransclusion
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/LabeledSectionTransclusion.git
      version: REL1_27
    - name: Cite
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Cite.git
      version: REL1_27
    - name: ParserFunctionHelper
      repo: https://github.com/enterprisemediawiki/ParserFunctionHelper.git
      version: master
    - name: WhoIsWatching
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/WhoIsWatching.git
      version: REL1_27
    - name: CharInsert
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/CharInsert.git
      version: REL1_27
    - name: SemanticForms
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/SemanticForms.git
      version: tags/3.5
    - name: SemanticInternalObjects
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/SemanticInternalObjects.git
      version: REL1_27
    - name: SemanticCompoundQueries
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/SemanticCompoundQueries.git
      version: REL1_27
    - name: Arrays
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Arrays.git
      version: REL1_27
    - name: TalkRight
      repo: https://github.com/enterprisemediawiki/TalkRight.git
      version: extreg
    - name: AdminLinks
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/AdminLinks.git
      version: REL1_27
    - name: DismissableSiteNotice
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/DismissableSiteNotice.git
      version: REL1_27
    - name: BatchUserRights
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/BatchUserRights.git
      version: REL1_27
    - name: HeaderTabs
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/HeaderTabs.git
      version: REL1_27
    - name: WikiEditor
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/WikiEditor.git
      version: REL1_27
    - name: CopyWatchers
      repo: https://github.com/jamesmontalvo3/MediaWiki-CopyWatchers.git
      version: extreg
    - name: SyntaxHighlight_GeSHi
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/SyntaxHighlight_GeSHi.git
      version: REL1_27
    - name: Wiretap
      repo: https://github.com/enterprisemediawiki/Wiretap.git
      version: extreg
    - name: ApprovedRevs
      repo: https://github.com/jamesmontalvo3/MediaWiki-ApprovedRevs.git
      version: master
    - name: InputBox
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/InputBox.git
      version: REL1_27
    - name: ReplaceText
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/ReplaceText.git
      version: REL1_27
    - name: Interwiki
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Interwiki.git
      version: REL1_27
    - name: MasonryMainPage
      repo: https://github.com/enterprisemediawiki/MasonryMainPage.git
      version: extreg
    - name: WatchAnalytics
      repo: https://github.com/enterprisemediawiki/WatchAnalytics.git
      version: master
    - name: Variables
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Variables.git
      version: REL1_27
    - name: YouTube
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/YouTube.git
      version: REL1_27
    - name: ContributionScores
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/ContributionScores.git
      version: REL1_27

    # @todo: The "official" version of this is in an SVN repository. If we need
    #        this it should be migrated to Gerrit or an EMW managed git repo.
    #        See https://www.mediawiki.org/wiki/Extension:Pipe_Escape
    - name: PipeEscape
      repo: https://github.com/jamesmontalvo3/MediaWiki-PipeEscape.git
      version: extreg
    - name: UniversalLanguageSelector
      repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/UniversalLanguageSelector.git
      version: REL1_27
    - name: VisualEditor
      repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/VisualEditor.git
      version: REL1_27
    - name: Elastica
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Elastica.git
      version: REL1_27
    - name: CirrusSearch
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/CirrusSearch.git
      version: REL1_27
    - name: Echo
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Echo.git
      version: REL1_27
    - name: Thanks
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Thanks.git
      version: REL1_27
    - name: UploadWizard
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/UploadWizard
      version: REL1_27
    - name: CollapsibleVector
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/CollapsibleVector
      version: REL1_27
    - name: Math
      repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/Math.git
      version: REL1_27
    - name: DataTransfer
      repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/DataTransfer.git
      version: tags/0.6.2


echo "******* Installing VE *******"
cd "$m_mediawiki/extensions/VisualEditor"
git submodule update --init

- name: Composer install Elastica dependencies
  composer:
    command: install
    working_dir: "{{ m_mediawiki }}/extensions/Elastica"

- name: Composer install SyntaxHighlight_GeSHi dependencies
  composer:
    command: install
    working_dir: "{{ m_mediawiki }}/extensions/SyntaxHighlight_GeSHi"

# Handle this with MediaWiki's "install" command?
# - name: Install composer-supported extensions
#   composer:
#     command: require
#     arguments: "{{ item }}"
#     working_dir: "{{ m_mediawiki }}"
#     with_items:
#       - mediawiki/semantic-media-wiki:~2.4
#       - mediawiki/semantic-result-formats:~2.0
#       - mediawiki/sub-page-list:~1.1
#       - mediawiki/semantic-meeting-minutes:~0.3
#       - mediawiki/semantic-maps:~3.2





#
# Install Demo MW: create wiki directory, setup basic settings, create database
#
echo -e "\n\nCreating new wiki called \"Demo Wiki\""
imports_dir="new"
wiki_id="demo"
wiki_name="Demo Wiki"
temp_slack="$slackwebhook" # don't notify when Demo Wiki is created.
slackwebhook="n"
source "$m_meza/scripts/create-wiki.sh"
slackwebhook="$temp_slack"



# FIXME
# FIXME
# FIXME
# FIXME
# FIXME
# FIXME: doesn't exist
- name: Run update.php on all wikis
  shell: php DOBACKUP.php
- name: Run update.php on all wikis
  shell: php /opt/meza/scripts/allwikis-update.php


# Import pages required for SemanticMeetingMinutes and rebuild indices
echo -e "\n\n## meza: import pages for SemanticMeetingMinutes"
WIKI=demo php maintenance/importDump.php --report --debug < ./extensions/SemanticMeetingMinutes/ImportFiles/import.xml
echo -e "\n\n## meza: rebuildrecentchanges.php"
WIKI=demo php maintenance/rebuildrecentchanges.php

#
# Create "Admin" user on Demo Wiki
# This is sort of strange in this location, but it cannot be done much prior to
# this due to the fact that everything defined in our pre-built LocalSettings.php
# must be available prior to running any maintenance scripts. Thus, it must be
# after SMW install due to the `enableSemantics()` function in LocalSettings.php.
# Other extensions could cause similar issues, so it's best that this go after
# loading extensions.
#
WIKI=demo php "$m_mediawiki/maintenance/createAndPromote.php" --force --custom-groups="sysop bureaucrat" Admin adminpass

#
# Generate ES index, since it is skipped in the initial create-wiki.sh
#
# Ref: https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FCirrusSearch.git/REL1_25/README
#
#
echo "******* Running elastic-build-index.sh *******"
wiki_id=demo
source "$m_meza/scripts/elastic-build-index.sh"


# NOTE: I think this can be in LocalSettings.php to start. Don't think it needs to be added later.
# Add "$wgSearchType = 'CirrusSearch';" to LocalSettings.php to funnel queries to ElasticSearch

