---


- name: Get individual wikis from controller config
  find:
    paths: "{{ m_local_public }}/wikis/"
    file_type: directory
  register: wiki_dirs
  delegate_to: localhost

- name: Ensure backups directory exists for environment
  file:
    path: "{{ m_backups }}/{{ env }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure backups directory exists for each wiki
  file:
    path: "{{ m_backups }}/{{ env }}/{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items: "{{ wiki_dirs.files | map(attribute='path') | map('basename') | list }}"

# copy from server A (db-master) to server B (backups)
- name: Copy SQL files to backups
  synchronize:
    # copy from server A
    src: "{{ m_tmp }}/{{ env }}_{{ item }}.sql"
    # copy to server B
    dest: "{{ m_backups }}/{{ env }}/{{ item }}/{{ backup_timestamp }}_wiki.sql"
  # server A
  delegate_to: "{{ groups['db-master'][0] }}"
  with_items: "{{ wiki_dirs.files | map(attribute='path') | map('basename') | list }}"

# Remove temp SQL files, only needs to be done on first backup server
- name: Remove SQL files from DB master {{ m_tmp }}
  file:
    path: "{{ m_tmp }}/{{ env }}_{{ item }}.sql"
    state: absent
  delegate_to: "{{ groups['db-master'][0] }}"
  with_items: "{{ wiki_dirs.files | map(attribute='path') | map('basename') | list }}"
  run_once: true
