---
- name: Install apache packages
  yum: name={{item}} state=installed
  with_items:
    - httpd-devel
    - mod_ssl
    - mod_proxy_html

- name: Make apache own htdocs directory
  file:
    state: directory
    path: "{{ m_htdocs }}"
    owner: apache
    group: apache
    mode: 0775

- name: Ensure user meza-ansible and alt-meza-ansible in group "apache"
  user:
    name: "{{ item }}"
    # add onto groups
    groups: apache
    append: yes
  with_items:
  - meza-ansible
  - alt-meza-ansible

- name: write the apache config file
  template: "src=httpd.conf.j2 dest={{ m_apache_conf }}"
  notify:
  - restart apache

# FIXME: required?
# create logrotate file
# ln -s " $m_config_core/logrotated_httpd" /etc/logrotate.d/httpd


# FIXME: apache.sh had commented-out SELinux commands for services

- name: Install PHP
  include: php.yml
  # http://docs.ansible.com/ansible/playbooks_roles.html#dynamic-versus-static-includes
  static: yes



# Only required for developers and performance testing
- name: Install XHProf PECL package for profiling
  pear:
    name: pecl/xhprof-beta
    state: present
  when: m_setup_php_profiling

- name: "Ensure {{ m_profiling_directory }} exists"
  file:
    path: "{{ m_profiling_directory }}"
    owner: apache
    group: apache
    mode: 0755
    state: directory
  when: m_setup_php_profiling

- name: Install graphviz packages
  yum:
    name: graphviz
    state: installed
  when: m_setup_php_profiling



# Now that PHP is installed, start apache
- name: ensure apache is running (and enable it at boot)
  service:
    name: httpd
    state: started
    enabled: yes
  when: docker_skip_tasks is not defined or not docker_skip_tasks



# Might need these for SELinux to be turned back on
# - name: Configure SELinux to start mysql on any port
#   seboolean: name=mysql_connect_any state=true persistent=yes
#   when: sestatus.rc != 0
# - name: Configure SELinux to allow httpd to connect to remote database
#   seboolean: name=httpd_can_network_connect_db state=true persistent=yes
#   when: sestatus.rc != 0
