---
- name: Install IUS (CentOS) repo.
  yum:
    name: "https://centos{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm"
  when: ansible_distribution == "CentOS"

- name: Install IUS (RHEL) repo.
  yum:
    name: "https://rhel{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm"
  when: ansible_distribution == "RedHat"

- name: Import IUS Community Project GPG key
  rpm_key:
    key: http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY
    state: present


- name: Remove PHP 5.x packages
  package:
    lock_timeout: 180 # wait up to 3 minutes for a lock ansible/ansible#57189
    name: "php5*"
    state: absent

# Check if the desired version of PHP is installed. If it is not, ensure any
# other versions of PHP are not installed
- name: "Check if {{ php_ius_version }} package is installed"
  yum:
    list: "{{ php_ius_version }}"
  register: correct_php

- debug:
    var: correct_php

- name: Remove any other PHP packages from IUS repo if correct PHP is not installed
  package:
    name: "php*u*"
    state: absent
  when: correct_php.results|length == 0

- name: Ensure PHP IUS packages installed
  yum:
    name:
      # The following items exist in php56u, php70u, php71u, and php72u
      - "{{ php_ius_version }}"
      - "{{ php_ius_version }}-cli"
      - "{{ php_ius_version }}-common"
      - "{{ php_ius_version }}-devel"
      - "{{ php_ius_version }}-gd"
      - "{{ php_ius_version }}-pspell"
      - "{{ php_ius_version }}-snmp"
      - "{{ php_ius_version }}-xml"
      - "{{ php_ius_version }}-xmlrpc"
      - "{{ php_ius_version }}-mysqlnd"
      - "{{ php_ius_version }}-pdo"
      - "{{ php_ius_version }}-odbc"
      - "{{ php_ius_version }}-process"
      - "{{ php_ius_version }}-bcmath"
      - "{{ php_ius_version }}-intl"
      - "{{ php_ius_version }}-opcache"
      - "{{ php_ius_version }}-soap"
      - "{{ php_ius_version }}-mbstring"
      - "{{ php_ius_version }}-ldap"

      # php56u has memcache and memcached; php7Xu only has memcached
      # legacy Meza used php56u-pecl-memcache
      - "{{ php_ius_version }}-pecl-memcached"

      # Available for php56u, php70u, and php71u. NOT for php72u.
      # - "php-mcrypt"

      # Available for php56u and php70u. NOT php71u or php72u
      # - "{{ php_ius_version }}-pear"
      # Post 7.0, use the pear1u package for all versions of PHP
      # PEAR is no longer a requirement for Meza. Mail and Net_SMTP installed with
      # Composer via MW core (MW 1.32+) or composer.local.json (MW 1.31 and lower)
      # - pear1u

      # Not available for PHP 7, due to being built into PHP 7
      # - php56u-pecl-jsonc

      # Not available in PHP 7
      # Get alternative method of accessing SQL Server:
      # https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-red-hat-7
      # - php56u-mssql
    state: present
