---
- name: Install php dependency packages
  package:
    name: "{{ package_php_apache_deps }}"
    state: present

- name: Install PHP (RedHat/CentOS only)
  include: php-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Install PHP (Debian only)
  include: php-debian.yml
  when: ansible_os_family == "Debian"

- name: Install MS SQL driver for PHP (FIXME RedHat only for now)
  include: mssql_driver_for_php.yml
  when:
    - install_ms_sql_driver is defined
    - install_ms_sql_driver
    - ansible_os_family == "RedHat"

- name: Write php.ini file
  template:
    src: php.ini.j2
    dest: "{{ m_php_ini }}"
  notify:
    - restart apache

- name: Write php.d ini files
  template:
    src: "{{ item }}.j2"
    dest: "{{ path_php_conf_d }}/{{ item }}"
  with_items: "{{ path_php_conf_d_files }}"
  notify:
    - restart apache

# FIXME: Is this left over from old method of supporting MSSQL? Not required now
#        that MS-provided drivers are used?
- name: Write freetds.conf file
  template:
    src: freetds.conf.j2
    dest: /etc/freetds.conf
  notify:
    - restart apache
  when: ansible_os_family == "RedHat"

- name: Ensure PEAR Mail and Net_SMTP packages installed
  pear:
    name: "{{ item }}"
    state: latest
  tags:
    - latest
  with_items:
    - Mail
    - Net_SMTP
