---

- name: Get individual wikis dirs from localhost
  find:
    paths: "{{ m_local_public }}/wikis/"
    file_type: directory
  register: wikis_dirs
  delegate_to: localhost

- set_fact:
    list_of_wikis: "{{ wikis_dirs.files | map(attribute='path') | map('basename') | list }}"

- name: Ensure localsettings.js present and up-to-date
  template:
    src: localsettings.js.j2
    dest: "{{ m_parsoid_path }}/localsettings.js"
  notify:
    - restart parsoid

- name: Ensure /etc/init.d/parsoid configured
  template:
    src: parsoid.initd.sh.j2
    dest: /etc/init.d/parsoid
    mode: 0755
  notify:
    - reload systemd
    - restart parsoid

- name: Enable parsoid service
  service:
    name: parsoid
    state: started
    enabled: yes
  when: docker_skip_tasks is not defined or not docker_skip_tasks
