---
list:

  - name: Scribunto
    repo: https://github.com/wikimedia/mediawiki-extensions-Scribunto.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgScribuntoDefaultEngine = 'luasandbox';
      $wgScribuntoUseGeSHi = true;
      $wgScribuntoUseCodeEditor = true;

  - name: SubPageList
    composer: "mediawiki/sub-page-list"
    version: "1.6.1"

  - name: Maps
    composer: "mediawiki/maps"
    version: "9.0.7"
    config: |
      // In Maps 6.0+ you need to also load the extension
      wfLoadExtension( 'Maps' );

  - name: DisplayTitle
    repo: https://github.com/wikimedia/mediawiki-extensions-DisplayTitle.git
    version: "{{ mediawiki_default_branch }}"


  #
  # Extensions loaded with wfLoadExtension
  #
  - name: ParserFunctions
    repo: https://github.com/wikimedia/mediawiki-extensions-ParserFunctions.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      // Also enable StringFunctions, like len, pos, sub, replace, explode
      // https://www.mediawiki.org/wiki/Extension:StringFunctions
      $wgPFEnableStringFunctions = true;

  - name: ExternalData
    repo: https://github.com/wikimedia/mediawiki-extensions-ExternalData.git
    version: "{{ mediawiki_default_branch }}"

  - name: LabeledSectionTransclusion
    repo: https://github.com/wikimedia/mediawiki-extensions-LabeledSectionTransclusion.git
    version: "{{ mediawiki_default_branch }}"

  - name: Cite
    repo: https://github.com/wikimedia/mediawiki-extensions-Cite.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgCiteEnablePopups = true;

  # Verify 34.x functionality
  - name: ParserFunctionHelper
    repo: https://github.com/enterprisemediawiki/ParserFunctionHelper.git
    version: tags/1.0.0

  - name: CharInsert
    repo: https://github.com/wikimedia/mediawiki-extensions-CharInsert.git
    version: "{{ mediawiki_default_branch }}"

  - name: PageForms
    repo: https://github.com/wikimedia/mediawiki-extensions-PageForms.git
    version: "tags/5.3.4"
    config: |
      // If enabled all "red links" will bring up a form chooser
      $wgPageFormsLinkAllRedLinksToForms = false;

  - name: DismissableSiteNotice
    repo: https://github.com/wikimedia/mediawiki-extensions-DismissableSiteNotice.git
    version: "{{ mediawiki_default_branch }}"

  - name: WikiEditor
    repo: https://github.com/wikimedia/mediawiki-extensions-WikiEditor.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgDefaultUserOptions['usebetatoolbar'] = 1;
      $wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
      $wgDefaultUserOptions['wikieditor-publish'] = 1; # displays publish button
      $wgDefaultUserOptions['wikieditor-preview'] = 1; # Displays the Preview and Changes tabs

  # consider replacing with https://github.com/wikimedia/mediawiki-extensions-SyntaxHighlight_Pygments.git
  - name: SyntaxHighlight_GeSHi
    repo: https://github.com/wikimedia/mediawiki-extensions-SyntaxHighlight_GeSHi.git
    version: "{{ mediawiki_default_branch }}"
    composer_merge: True

  - name: CodeEditor
    repo: https://github.com/wikimedia/mediawiki-extensions-CodeEditor.git
    version: "{{ mediawiki_default_branch }}"

  - name: InputBox
    repo: https://github.com/wikimedia/mediawiki-extensions-InputBox.git
    version: "{{ mediawiki_default_branch }}"

  - name: ReplaceText
    repo: https://github.com/wikimedia/mediawiki-extensions-ReplaceText.git
    version: "{{ mediawiki_default_branch }}"

  - name: Interwiki
    repo: https://github.com/wikimedia/mediawiki-extensions-Interwiki.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgGroupPermissions['sysop']['interwiki'] = true;

  - name: YouTube
    repo: https://github.com/wikimedia/mediawiki-extensions-YouTube.git
    version: "{{ mediawiki_default_branch }}"

  - name: UniversalLanguageSelector
    repo: https://github.com/wikimedia/mediawiki-extensions-UniversalLanguageSelector
    version: "{{ mediawiki_default_branch }}"
    config: |
      // Disable international phoenetic alphabet selector that breaks searching for
      // English users. From docs:
      //
      // $wgULSIMEEnabled - Disable the input methods feature for all users by
      // default. Can still be enabled manually by the user.
      //
      // Refs:
      //
      // https://www.mediawiki.org/wiki/Help:Extension:UniversalLanguageSelector/Input_methods
      // https://www.mediawiki.org/wiki/Extension:UniversalLanguageSelector
      $wgULSIMEEnabled = false;

  - name: VisualEditor
    repo: https://github.com/wikimedia/mediawiki-extensions-VisualEditor.git
    version: "{{ mediawiki_default_branch }}"
    git_submodules: True
    config: |
      // Show visual diff on regular diff pages
      $wgVisualEditorEnableDiffPage = true;

      // Enable by default for everybody
      $wgDefaultUserOptions['visualeditor-enable'] = 1;

      // Don't allow users to disable it
      $wgHiddenPrefs[] = 'visualeditor-enable';

      // OPTIONAL: Enable VisualEditor's experimental code features
      // $wgDefaultUserOptions['visualeditor-enable-experimental'] = 1;

      $wgVisualEditorAvailableNamespaces = [
          "User" => true,
          "Project" => true,
          "Help" => true,
          "_merge_strategy" => "array_plus"
      ];

      // quickly add a namespace, without figuring out what the merge strategy is
      // $wgVisualEditorAvailableNamespaces[] = NS_CUSTOM;
      // $wgVisualEditorAvailableNamespaces[] = NS_PROJECT;

      // None of this appears to be necessary anymore in MW 1.35 (and having it breaks VE)
      // $wgVirtualRestConfig['modules']['parsoid'] = array(
      //     'url' => "http://127.0.0.1:8080/$wikiId/rest.php",
      // );
      // Because we're manually setting the Virtual Rest Config above, need to load Parsoid manually
      // wfLoadExtension( 'Parsoid', '{{ m_mediawiki }}/vendor/wikimedia/parsoid/extension.json' );

  - name: TemplateData
    repo: https://github.com/wikimedia/mediawiki-extensions-TemplateData.git
    version: "{{ mediawiki_default_branch }}"

  - name: Elastica
    repo: https://github.com/wikimedia/mediawiki-extensions-Elastica.git
    version: "{{ mediawiki_default_branch }}"
    composer_merge: True

  - name: RevisionSlider
    repo: https://github.com/wikimedia/mediawiki-extensions-RevisionSlider.git
    version: "{{ mediawiki_default_branch }}"

  - name: CollapsibleVector
    repo: https://github.com/wikimedia/mediawiki-extensions-CollapsibleVector
    version: 7b71b1b04cc77eb4621e55b3dda6b9e15f4dd029

  - name: SimpleMathJax
    repo: https://github.com/jamesmontalvo3/SimpleMathJax.git
    version: e94afaffcdde8d926b166fdd166162f9519beaa1
    legacy_load: True

  - name: ImageMap
    repo: https://github.com/wikimedia/mediawiki-extensions-ImageMap
    version: "{{ mediawiki_default_branch }}"

  # Verify 34.x functionality
  - name: MezaExt
    repo: https://github.com/enterprisemediawiki/MezaExt.git
    version: tags/0.1.0

  # Extension:PdfHandler (breaks on very large PDFs)
  # https://github.com/wikimedia/mediawiki-extensions-PdfHandler
  # // Location of PdfHandler dependencies
  # // $wgPdfProcessor = '/usr/bin/gs'; // installed via yum
  # // $wgPdfPostProcessor = '/usr/local/bin/convert'; // built from source
  # // $wgPdfInfo = '/usr/local/bin/pdfinfo'; // pre-built binaries installed




  #
  # Extensions loaded with legacy require_once method
  #
  - name: StringFunctionsEscaped
    repo: https://github.com/wikimedia/mediawiki-extensions-StringFunctionsEscaped.git
    version: "{{ mediawiki_default_branch }}"
    legacy_load: true

  - name: WhoIsWatching
    repo: https://github.com/wikimedia/mediawiki-extensions-WhoIsWatching.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgPageShowWatchingUsers = true;

  - name: Arrays
    repo: https://github.com/wikimedia/mediawiki-extensions-Arrays.git
    version: "8ffa3c6a4ae43824d8128c120ff25d569bae3d53"

  - name: AdminLinks
    repo: https://github.com/wikimedia/mediawiki-extensions-AdminLinks.git
    version: tags/0.5
    config: |
      $wgGroupPermissions['sysop']['adminlinks'] = true;

  - name: BatchUserRights
    repo: https://github.com/wikimedia/mediawiki-extensions-BatchUserRights.git
    version: "{{ mediawiki_default_branch }}"

  - name: HeaderTabs
    repo: https://github.com/wikimedia/mediawiki-extensions-HeaderTabs.git
    version: tags/1.3
    config: |
      $wgHeaderTabsEditTabLink = false;
      $wgHeaderTabsRenderSingleTab = true;

  # Verify 34.x functionality
  - name: CopyWatchers
    repo: https://github.com/V-Brooks/MediaWiki-CopyWatchers.git
    version: "4d66119f0cc3bbf9744952757e8bf737e7ab45e9"

  # Verify 34.x functionality
  - name: Wiretap
    repo: https://github.com/djflux/Wiretap.git
    version: "d70a56562ecd01cd3dec7f9e639a7e8f2898aaae"

  # Verify 34.x functionality
  - name: ImagesLoaded
    repo: https://github.com/enterprisemediawiki/ImagesLoaded.git
    version: tags/0.1.0

  # Verify 34.x functionality
  - name: MasonryMainPage
    repo: https://github.com/enterprisemediawiki/MasonryMainPage.git
    version: tags/0.3.0

  # Verify 34.x functionality
  - name: WatchAnalytics
    repo: https://github.com/wikimedia/mediawiki-extensions-WatchAnalytics.git
    version: tags/4.1.2
    config: |
      $egPendingReviewsEmphasizeDays = 10; // makes Pending Reviews shake after X days

  - name: Variables
    repo: https://github.com/wikimedia/mediawiki-extensions-Variables.git
    version: "8038bcabb4829f3f3845db97da9f9b157c8a606b"

  - name: ContributionScores
    repo: https://github.com/wikimedia/mediawiki-extensions-ContributionScores.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      // Exclude Bots from the reporting - Can be omitted.
      $wgContribScoreIgnoreBots = true;

      // Exclude Blocked Users from the reporting - Can be omitted.
      $wgContribScoreIgnoreBlockedUsers = true;

      // Use real user names when available - Can be omitted. Only for MediaWiki 1.19 and later.c
      $wgContribScoresUseRealName = true;

      // Set to true to disable cache for parser function and inclusion of table.
      $wgContribScoreDisableCache = false;

      // Each array defines a report - 7,50 is "past 7 days" and "LIMIT 50" - Can be omitted.
      $wgContribScoreReports = array(
        array(7,50),
        array(30,50),
        array(0,50)
      );

  - name: PipeEscape
    repo: https://github.com/wikimedia/mediawiki-extensions-PipeEscape.git
    version: "{{ mediawiki_default_branch }}"

  - name: CirrusSearch
    repo: https://github.com/wikimedia/mediawiki-extensions-CirrusSearch.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      // CirrusSearch cluster(s) are defined based upon Ansible hosts file and thus
      // cannot be easily added to MezaCoreExtensions.yml. As such, CirrusSearch config
      // is included directly in LocalSettings.php.j2

  - name: Echo
    repo: https://github.com/wikimedia/mediawiki-extensions-Echo.git
    version: "{{ mediawiki_default_branch }}"
    config: |
      $wgEchoEmailFooterAddress = $wgPasswordSender;

  - name: UploadWizard
    repo: https://github.com/wikimedia/mediawiki-extensions-UploadWizard
    version: "{{ mediawiki_default_branch }}"
    config: |
      // Needed to make UploadWizard work in IE, see bug 39877
      // See also: https://www.mediawiki.org/wiki/Manual:$wgApiFrameOptions
      $wgApiFrameOptions = 'SAMEORIGIN';

      // Use UploadWizard by default in navigation bar
      $wgUploadNavigationUrl = "$wgScriptPath/index.php/Special:UploadWizard";
      $wgUploadWizardConfig = array(
        'debug' => false,
        'autoCategory' => 'Uploaded with UploadWizard',
        'feedbackPage' => 'Project:UploadWizard/Feedback',
        'altUploadForm' => 'Special:Upload',
        'fallbackToAltUploadForm' => false,
        'enableFormData' => true,  # Should FileAPI uploads be used on supported browsers?
        'enableMultipleFiles' => true,
        'enableMultiFileSelect' => true,
        'tutorial' => array('skip' => true),
        'fileExtensions' => $wgFileExtensions, //omitting this can cause errors
        'licensing' => array(
          // alternatively, use "thirdparty". Set in postLocalSettings.php like:
          // $wgUploadWizardConfig['licensing']['defaultType'] = 'thirdparty';
          'defaultType' => 'ownwork',

          'ownWork' => array(
            'type' => 'or',
            // Use [[Project:General disclaimer]] instead of default [[Template:Generic]]
            'template' => 'Project:General disclaimer',
            'defaults' => array( 'generic' ),
            'licenses' => array( 'generic' )
          ),

          'thirdParty' => array(
            'type' => 'or',
            'defaults' => array( 'generic' ),
            'licenseGroups' => array(
              array(
                'head' => 'mwe-upwiz-license-generic-head',
                'template' => 'Project:General disclaimer', // again, use General disclaimer
                'licenses' => array( 'generic' ),
              ),
            )
          ),
        ),
      );

  - name: DataTransfer
    repo: https://github.com/wikimedia/mediawiki-extensions-DataTransfer.git
    version: "tags/1.1.1"

  - name: PageImporter
    repo: https://github.com/enterprisemediawiki/PageImporter.git
    version: tags/0.1.0
    legacy_load: True

  # Verify 34.x functionality
  - name: NumerAlpha
    repo: https://github.com/wikimedia/mediawiki-extensions-NumerAlpha.git
    version: "{{ mediawiki_default_branch }}"
