---

- name: Ensure secret config directory exists
  file:
    path: "{{ m_local_secret }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure secret config environment directory exists
  file:
    path: "{{ m_local_secret }}/{{ env }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure group_vars directory exists
  file:
    path: "{{ m_local_secret }}/{{ env }}/group_vars"
    state: directory
    owner: root
    group: root
    mode: 0755

# Ansible writing Ansible
- name: Ensure hosts file configured
  template:
    src: hosts.j2
    dest: "{{ m_local_secret }}/{{ env }}/hosts"

    # We don't want to overwrite an existing hosts file with the default
    force: no

- name: Ensure all.yml configured
  template:
    src: all.yml.j2
    dest: "{{ m_local_secret }}/{{ env }}/group_vars/all.yml"

    # don't overwrite existing
    force: no

- name: Ensure all.yml encrypted
  shell: >
    ansible-vault encrypt
    {{ m_local_secret }}/{{ env }}/group_vars/all.yml
    --vault-password-file /home/meza-ansible/.vault-pass-{{ env }}.txt
  ignore_errors: True
