---
# Run with command `meza maint rebuild $envName`
# Just search: `meza maint rebuild $envName --skip-tags smw-data`
# Just SMW: `meza maint rebuild $envName --skip-tags search-index`

- hosts: app_servers
  become: yes
  tasks:

  - name: Set vars
    include_role:
      name: set-vars
    tags:
    - always

  - name: (Re-)build search index for each wiki
    shell: "bash {{ m_deploy }}/elastic-rebuild-all.sh"
    run_once: true
    tags:
    - search-index

