---
list:
## THIS FILE IS AN EXAMPLE
##  You should copy it, or portions of it, to your meza controller host in the conf directory at /opt/conf-meza/public/MezaLocalExtensions.yml
##  Then use the script at /opt/meza/src/scripts/compareExtensions.php to understand exactly what extensions you need to add locally to support a migration of a third-party wiki.  See that script for help
- name: CategoryTree
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CategoryTree.git
  # CategoryTree didn't convert to extension registration until 1_28
  version: "{{ mediawiki_default_branch }}"
  config: |
    //    maximum number of children shown in a tree node. Default is 200.
    $wgCategoryTreeMaxChildren = 200;
    //    enable <categorytree> tag. Default is true.
    $wgCategoryTreeAllowTag = TRUE;
    //    loads the first level of the tree in a <categorytree> dynamically. This way, the cache does not need to be disabled. Default is false.
    $wgCategoryTreeDynamicTag = TRUE;
    //    disables the parser cache for pages with a <categorytree> tag. Default is true.
    $wgCategoryTreeDisableCache = FALSE;
    //    enable HTTP cache for anon users. Default is false.
    $wgCategoryTreeHTTPCache = TRUE;
    //    do not show the namespace name for pages and categories. Default is false, namespaces are shown unless showing categories only. Deprecated as of rev:36864, July 2008: use $wgCategoryTreeDefaultOptions['hideprefix'] instead.
    $wgCategoryTreeDefaultOptions['hideprefix'] =TRUE; // $wgCategoryTreeOmitNamespace
    //    an array defining the maximum depth for each mode, to which the tree may be expanded initially using the depth parameterin a <category> tag. Per default, this is set to 2 for the "categories" mode, and 1 for other modes. To set it to 3 for categories and 2 for other modes, for example, you can use $wgCategoryTreeMaxDepth = array(CT_MODE_PAGES => 2, CT_MODE_ALL => 2, CT_MODE_CATEGORIES => 3);.
    $wgCategoryTreeMaxDepth= array(CT_MODE_PAGES => 2, CT_MODE_ALL => 2, CT_MODE_CATEGORIES => 3);
    //    the default mode to use when no mode attribute is specified in a <categorytree> tag. May be CT_MODE_CATEGORIES (the default), CT_MODE_PAGES, or CT_MODE_ALL.
    $wgCategoryTreeDefaultMode = CT_MODE_ALL;
    //    the mode to use when rendering trees on category pages. Deprecated as of rev:36864, July 2008: use $wgCategoryTreeCategoryPageOptions['mode'] instead.
    $wgCategoryTreeCategoryPageOptions['mode'] = CT_MODE_ALL; // $wgCategoryTreeCategoryPageMode
    //    if true, forces the scripts needed by CategoryTree on every page, instead of on-demand. This may be needed if a CategoryTree is embedded in an unusualy way, for example in a custom skin or in a system message (since rev:36888, July 2008).
    // NOT WORKING in freephile skin $wgCategoryTreeSidebarRoot = 'People';
    //    root category to use for integrating the category tree in the sidebar (since rev:36920, July 2008). If not set, no tree is integrated (this is the default). Integrating a CategoryTree into the sidebar only works with skins based upon SkinTemplate,that is, Modern, Monobook, Chick, Simple, and MySkin, but not Standard, Nostalgia or CologneBlue.
    $wgCategoryTreeForceHeaders = TRUE;
    //    default options to apply, as an array (since rev:36864, July 2008). The avialable options are described above.
    $wgCategoryTreeDefaultOptions = array();
    //    options to use on category pages, as an array (since rev:36864, July 2008).
    $wgCategoryTreeCategoryPageOptions = array();
    //    options to use on Special:CategoryTree, as an array (since rev:36864, July 2008).
    $wgCategoryTreeSpecialPageOptions = array();
    //    options to use when showing the tree in the sidebar, as an array (since rev:36920, July 2008).
    $wgCategoryTreeSidebarOptions = array();



- name: ConfirmEdit
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ConfirmEdit.git
  version: "{{ mediawiki_default_branch }}"
- name: Gadgets
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Gadgets.git
  version: "{{ mediawiki_default_branch }}"
- name: MobileFrontend
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MobileFrontend.git
  version: "{{ mediawiki_default_branch }}"
  config: |
    $wgMFAutodetectMobileView = true;
- name: Nuke
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Nuke.git
  version: "{{ mediawiki_default_branch }}"
- name: Renameuser
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Renameuser.git
  version: "{{ mediawiki_default_branch }}"

#
# Extensions loaded with legacy require_once method
#

- name: CreateRedirect
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CreateRedirect.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
# possible widget? or just don't do it? or download the code manually
# - name: FollowButton
#   https://www.mediawiki.org/wiki/Extension:FollowButton
- name: Loops
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Loops.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
  config: |
    ExtLoops::$maxLoops = 5000;
- name: MagicNoCache
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MagicNoCache.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
- name: MyVariables
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MyVariables.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
- name: Widgets
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Widgets.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
  # this module requires a git submodule update --init; thus the next line
  git_submodules: True

#
# libraries loaded by composer
#
- name: DataValues
  #repo: https://github.com/DataValues/DataValues.git
  composer: "data-values/data-values"
  version: "~1.0"
- name: DataValuesCommon
  composer: "data-values/common"
  version: "0.3.*"
- name: DataValuesGeo
  composer: "data-values/geo"
  version: "1.2.*"
- name: DataValuesInterfaces
  composer: "data-values/interfaces"
  version: "0.2.*"
- name: DataValuesTime
  composer: "data-values/time"
  version: "0.8.*"
- name: DataValuesValidators
  composer: "data-values/validators"
  version: "0.1.*"
- name: ParserHooks
  composer: mediawiki/parser-hooks
  version: "~1.5"
- name: BetaFeatures
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/BetaFeatures
  version: "{{ mediawiki_default_branch }}"
- name: CSS
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/CSS.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
- name: CategorySuggest
  repo: https://github.com/middlebury/CategorySuggest.git
  version: tags/CategorySuggest-1.8
  legacy_load: True
- name: WikiCategoryTagCloud
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikiCategoryTagCloud
  version: "{{ mediawiki_default_branch }}"
- name: CiteThisPage
  repo: https://gerrit.wikimedia.org/r/mediawiki/extensions/CiteThisPage.git
  version: "{{ mediawiki_default_branch }}"
