---
- name: Ensure user meza-ansible in group "wheel"
  user:
    name: meza-ansible
    # primary group
    group: wheel

- name: ensure deltarpm is installed and latest
  yum: name=deltarpm state=installed
- name: upgrade all packages
  yum: name=* state=latest

# FIXME: for RedHat may need to enable "Optional RPMs"
- name: ensure EPEL installed
  yum:
    name: epel-release
    state: installed
  when: ansible_distribution == "CentOS"

- name: Check if EPEL repo is already configured.
  stat:
    path: "/etc/yum.repos.d/epel.repo"
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: ansible_distribution == "RedHat" and not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  when: ansible_distribution == "RedHat" and not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"


- name: Ensure optional repos enabled
  shell: subscription-manager repos --enable rhel-7-server-optional-rpms
  when: ansible_distribution == "RedHat"


- name: ensure libselinux-python installed prior to SELinux
  yum: name=libselinux-python state=installed
- name: Install base packages
  yum: name={{item}} state=installed
  with_items:
    - ntp
    - ntpdate
    - ntp-doc
    - openssh-server
    - openssh-clients
    - vim
    - git
    - net-tools
    - firewalld
    - selinux-policy
    - rsyslog
    - jq
    - tree
- name: put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive # log actions that would be blocked if state=enforcing
- name: ensure firewalld is running (and enable it at boot)
  service: name=firewalld state=started enabled=yes
  when: docker_skip_tasks is not defined or not docker_skip_tasks
# FIXME: These were not in non-ansible meza, but was present in the firewalld
#        role I co-opted.
# - name: set firewalld default zone
#   command: /bin/firewall-cmd --set-default-zone={{default_zone|default('public')}}
#   register: result
#   changed_when: result.stdout == "success"
# - name: set firewalld zone interface
#   command: /bin/firewall-cmd --zone={{item.key}} --change-interface={{item.value}} --permanent
#   with_dict: "{{firewalld_zone_interface|default({})}}"
#   notify: restart firewalld

# Replace the following shell commands:
# chkconfig ntpd on # Activate service
# ntpdate pool.ntp.org # Synchronize the system clock with 0.pool.ntp.org server
# service ntpd start # Start service
- name: Install NTP
  yum: name=ntp state=installed
- name: Ensure NTP is running and enabled as configured.
  service:
    name: ntpd
    state: started
    enabled: yes
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd

# - name: Write local config shell file
#   template:
#     src: config.sh.j2
#     dest: /opt/meza/config/config.sh

# - name: Write local config PHP file
#   template:
#     src: config.php.j2
#     dest: /opt/meza/config/config.php
