---
- name: Ensure ghostscript installed
  package:
    name: ghostscript
    state: present

- name: Install Imagemagick from meza repo (RedHat/CentOS only)
  yum:
    name: https://raw.github.com/enterprisemediawiki/meza-packages/master/RPMs/imagemagick_7.0.3_x86_64.rpm
  when: ansible_os_family == 'RedHat'

# FIXME: Is this okay? I think this installs an older version...
- name: Ensure Imagemagick installed (Debian only)
  apt:
    name: imagemagick
    state: present
  when: ansible_os_family == 'Debian'

- name: Copy xpdf bin64 files to /usr/local/bin
  copy:
    src: xpdf-3.04-bin64/
    dest: /usr/local/bin/
