---

# inputs:
#   wiki_id
#   wiki_name
#
# all this role needs to do is put a directory named whatever wiki_id is at
# /opt/meza/local/wikis/<wiki_id>
#
# This role DOES NOT actually deploy the wiki to app servers or database
# servers. It simply puts it into configuration. Subsequently it can be
# deployed.
#
# This directory needs to have some minimum requirements:
#   logo.png (is .jpg also allowed?)
#   original.png (is .jpg also allowed? Is this really required?)
#   favicon.ico
#   preLocalSettings.php
#   postLocalSettings.php

- name: Ensure wiki directory exists in config
  file:
    path: "/opt/meza/config/local_control/wikis/{{ wiki_id }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755
  delegate_to: localhost
  run_once: true

# This will make sure the wiki has some required files, but if they exist
# already it will not overwrite them.
- name: Ensure base files are in place (but do not overwrite)
  copy:
    src: "files/{{ item }}"
    dest: "/opt/meza/config/local_control/wikis/{{ wiki_id }}/{{ item }}"
    # force=no: this will not overwrite
    force: no
    owner: apache
    group: apache
    mode: 0755
  with_items:
    - favicon.ico
    - logo.png
    - this-wiki-more-extensions.yml
  delegate_to: localhost
  run_once: true

- name: Ensure base templates are present (but do not overwrite)
  template:
    src: "templates/{{ item }}.j2"
    dest: "/opt/meza/config/local_control/wikis/{{ wiki_id }}/{{ item }}"
    # force=no: Non-default for templates. Destination files will not be overwritten
    force: no
    owner: apache
    group: apache
    mode: 0755
  with_items:
    - preLocalSettings.php
    - postLocalSettings.php
  delegate_to: localhost
  run_once: true
