---

- hosts: all
  become: yes
  vars_files:
    - "paths.yml"
  roles:
    - base
    # FIXME: add "security" module here

- hosts: load-balancers
  become: yes
  vars_files:
    - "paths.yml"
  roles:
    - haproxy
