---
# run with:
# cd /opt/meza/ansible
# sudo -u meza-ansible ansible-playbook site.yml

- hosts: all
  become: yes
  roles:
    - base
    # FIXME: add "security" module here
- hosts: app-servers
  become: yes
  roles:
    - base-extras
    - imagemagick
    - apache-php
    - memcached # Note this should move to separate server(s)

- hosts: db-master
  become: yes
  vars_files:
    - vars/database.yml
  roles:
    - role: firewalld
      firewalld_service: mysql
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: public  # "{{ m_private_networking_zone }}"
    - role: firewalld
      firewalld_service: mysql
      firewalld_servers: "{{ groups['db-slaves'] }}"
      firewalld_zone: public
    - database

- hosts: db-slaves
  become: yes
  vars_files:
    - vars/database.yml
  roles:
    - role: firewalld
      firewalld_service: mysql
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: public
    - database



# - hosts: parsoid-servers
#   become: yes
#   roles:
#     - parsoid
# - hosts: elastic-servers
#   become: yes
#   roles:
#     - elasticsearch

# Note: this is app-servers again, but must be after everything else is setup
# - hosts: app-servers
#   become: yes
#   roles:
#     - mediawiki
    # - extensions # any reason to separate MW and extensions?

