---
# run with:
# cd /opt/meza/ansible
# sudo -u meza-ansible ansible-playbook site.yml

- hosts: all
  become: yes
  roles:
    - base
    # FIXME: add "security" module here
- hosts: app-servers
  become: yes
  roles:
    - base-extras
    - imagemagick
    - apache-php
    - composer
    - memcached # Note this should move to separate server(s)

- hosts: db-master
  become: yes
  tags: database
  vars_files:
    - vars/database.yml
  pre_tasks:
    - debug: { msg: "Replication master = {{mysql_replication_master}}" }
    - debug: { var: mysql_replication_role }
    - debug: { var: mysql_replication_user }
  roles:
    - role: firewalld
      firewalld_service: mysql
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: public  # "{{ m_private_networking_zone }}"
    - role: firewalld
      firewalld_service: mysql
      firewalld_servers: "{{ groups['db-slaves'] }}"
      firewalld_zone: public
    - database

- hosts: db-slaves
  become: yes
  tags: database
  vars_files:
    - vars/database.yml
  pre_tasks:
    - debug: { msg: "Replication master = {{mysql_replication_master}}" }
    - debug: { var: mysql_replication_role }
    - debug: { var: mysql_replication_user }
  roles:
    - role: firewalld
      firewalld_service: mysql
      firewalld_servers: "{{ groups['app-servers'] }}"
      firewalld_zone: public
    - database

- hosts: parsoid-servers
  become: yes
  tags: parsoid
  roles:
    - nodejs
    - parsoid

- hosts: elastic-servers
  become: yes
  tags: elasticsearch
  roles:
    - elasticsearch

# Note: this is app-servers again, but must be after everything else is setup
- hosts: app-servers
  become: yes
  tags: mediawiki
  roles:
    - mediawiki

