---
"on":
  # Trigger the workflow on pushes to these branches
  push:
    branches:
      - master
      - 34.x
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print working directory
        run: pwd

      - name: List files in working directory
        run: ls -al

      - name: Make target directory for sources
        run: mkdir -p /opt/meza
      
      - name: Copy code
        run: sudo cp -r ${{ github.workspace }} /opt/

      - name: Install prerequisites
        run: sudo apt install -y git ansible
      
      # - name: Clone Meza
      #   run: sudo git clone https://github.com/freephile/meza /opt/meza
      
      - name: Run "getmeza with sudo -H to avoid cache warnings"
        run: sudo -H bash /opt/meza/src/scripts/getmeza.sh
      
      - name: Setup the monolith environment
        run: sudo meza setup env monolith --fqdn="127.0.0.1" --db_pass=1234 --private_net_zone=public

      # The --no-firewall option does not exist
      - name: Deploy Meza
        run: sudo meza deploy monolith

      - name: Print hosts file as a rudimentary "test"
        run: cat /opt/conf-meza/secret/monolith/hosts
