---
"on":
  # Trigger the workflow on pushes to these branches
  push:
    branches:
      - master
      - 34.x
jobs:
  one:
    # ubuntu-18.04
    # runs-on: ubuntu-latest 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # GitHub Runners include a LOT of software by default
      # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
      - name: Uninstall MySQL so we can use MariaDB
        run: sudo apt-get remove --purge mysql-server

      - name: Make target directory for sources
        run: mkdir -p /opt/meza
      
      - name: Copy code
        run: sudo cp -r ${{ github.workspace }} /opt/

      - name: Install prerequisites
        run: sudo apt install -y git ansible
      
      # - name: Clone Meza
      #   run: sudo git clone https://github.com/freephile/meza /opt/meza
      
      - name: Run "getmeza with sudo -H to avoid cache warnings"
        run: sudo -H bash /opt/meza/src/scripts/getmeza.sh
      
      - name: Setup the monolith environment
        run: sudo meza setup env monolith --fqdn="127.0.0.1" --db_pass=1234 --private_net_zone=public

      # The --no-firewall option does not exist
      - name: Deploy Meza
        run: sudo meza deploy monolith -vvv

      - name: Print hosts file as a rudimentary "test"
        run: cat /opt/conf-meza/secret/monolith/hosts
