---
"on":
  # Trigger the workflow on pushes to these branches
  push:
    branches:
      - master
      - 34.x
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -al 
      
      # - name: Move code
      #   run: sudo mv $GITHUB_WORKSPACE /opt/meza
      # - name: Install prerequisites
      #   run: sudo apt install -y git ansible
      # # - name: Clone Meza
      # #   run: sudo git clone https://github.com/freephile/meza /opt/meza
      # - name: Run "get meza"
      #   run: sudo bash /opt/meza/src/scripts/getmeza.sh
      # - name: Deploy monolith
      #   run: sudo meza deploy monolith

