---
"on":
  # Trigger the workflow on pushes to these branches
  push:
    branches:
      - master
      - 34.x
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print working directory
        run: pwd

      - name: List files in working directory
        run: ls -al

      - name: Make target directory for sources
        run: mkdir -p /opt/meza
      
      - name: Copy code
        run: sudo cp -r ${{ github.workspace }} /opt/

      # - name: List files in /opt/meza
      #   run: ls -al /opt/meza

      - name: Install prerequisites
        run: sudo apt install -y git ansible
      
      # - name: Clone Meza
      #   run: sudo git clone https://github.com/freephile/meza /opt/meza
      
      - name: Run "get meza"
        run: sudo -H bash /opt/meza/src/scripts/getmeza.sh
      
      - name: Deploy monolith
        run: sudo meza deploy monolith

