---
"on":
  # Trigger the workflow on pushes to these branches
  push:
    branches:
      - master
      - 34.x
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    #   - uses: actions/checkout@v2
    #     with:
    #       path: /opt/meza

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install prerequisites
        run: apt install -y git ansible
      - name: Clone Meza
        run: git clone https://github.com/freephile/meza /opt/meza
      - name: Run "get meza"
        run: bash /opt/meza/src/scripts/getmeza.sh
      - name: Deploy monolith
        run: meza deploy monolith

